### ISSUE TITLE
Missing hyperlink to category list for powers

### ISSUE THREAD

**Issue by asaucedev** [CBLoader/CBLoader#3]
https://github.com/CBLoader/CBLoader/wiki/Custom-Powers
The following paragraph alludes to a hyperlink which is not present.

On the Custom Powers page:
"The next categories are keywords for the attack. The keywords for this attack are Charm, Divine, Implement, and Radiant, and their corresponding categories are ID_FMP_CATEGORY_6, ID_FMP_CATEGORY_32, ID_FMP_CATEGORY_25, and ID_FMP_CATEGORY_2. When you add keywords to your power, you need to make sure that the corresponding keyword category is in here. The full list is here."

**Comment by silasary** [comment]
Ah, thanks. I'll try to figure out where that linked to

**Comment by silasary** [comment]
Transcribing tables into markdown is painful
https://github.com/CBLoader/CBLoader/wiki/Category-Reference
