### ISSUE TITLE
Lost most of content on update

### ISSUE THREAD

**Issue by falconflicker** [CBLoader/CBLoader#6]
I tried to run the program today, and it updated data, removing the vast majority of the WotC data.
I managed to save it by renaming all of the files so that new updates don't overwrite the old ones, but it's really annoying that those files were changed.

**Comment by Jigurd** [comment]
Same problem. Some reading of WotC.index in Documents/ddi/CBLoader seems like it's pulling data from CBloader.com, which seems to be a domain no longer in use.

**Comment by euchronicity** [comment]
There's a fork of CBLoader that's been updated more recently, including changes to merges, at https://github.com/Lymia/CBLoader.

**Comment by silasary** [comment]
Oooh, nice, I'll merge those updates in.

As for the cbloader.com issue, I'm getting a full mirror of that domain up now.  I'll post it shortly :)

**Comment by Tuttu** [comment]
Any news about that @silasary ?

**Comment by silasary** [comment]
I've lost the 3rd party stuff, if anyone had it, please let me know.

But the WotC updates have been mirrored at
http://vorpald20.com/cbloader/WotC.index

>

**Comment by Tuttu** [comment]
Thanks a lot. I will check if I have some that you don't have. If so, I will upload them here as a pull request. :)

**Comment by Tuttu** [comment]
After checking, you have more modules than I had so I have nothing else to add. Thanks again for mirroring all the stuff. :)

**Comment by sisco1986** [comment]
iam getting errors again with the wotc.index that silasary provided

ERROR: Failed checking for Updates
Inner Exception: The underlying connection was closed: An unexpected error occurred on a send.
Inner Exception:    Received an unexpected EOF or 0 bytes from the transport stream.

**Comment by Tuttu** [comment]
@sisco1986 Everything looks fine for me. Did you tried again? Maybe the mirror was temporarily unreachable.

**Comment by sisco1986** [comment]
@Tuttu i uninstalled this version and installed the fork that euchronicity provided and it worked perfectly

**Comment by ryancox111** [comment]
These steps should work to solve the problem.

Issue: CBLoader.com stopped maintain the domain and the domain became owned by on of the domain hosting companies.  Now when you start the program it will try to connect to the domain and will be supplied invalid part files and will erase all custom rules.  

Fix: Update your shortcut to add option -d.  This prevents the download update step. Example = "...\Wizards of the Coast\Character Builder\CBLoader.exe" -d

To Fix after it has been broken by connecting to the server.

1) Redownload all part files and place them in Customer folder.
2) using command prompt run cbloader with options -e (forces re-sync) -n (does not execute exe) and -d (does not download).
3) Update your shortcut to add option -d (does not download).

**Comment by thugsb** [comment]
@euchronicity how do I use/install your branch of the CBLoader? I installed the CBLoader from a torrent several years ago, including the 2009 and 2010 updates. I was then using it for several years, getting the updates. But now much of the data is gone. I'd like to use your branch, yet I'm unsure how to install it or build it or whatever. A readme would really help. Thanks!

@ryancox111 Where is the Customer folder you mention? I'm not seeing it in the Program Files folder of the Character Builder. Or is this something that exists once I install/build this git repo?

Thanks for the help all! Glad people are still updating this! :)

**Comment by euchronicity** [comment]
thugsb - That's not my fork, just one I found by looking for forks on GitHub.

**Comment by silasary** [comment]
bb05a2a4489b7e1c1bb6c1a4502c2ca56fa1e7ec added code to prevent this from happening again.
